### ISSUE TITLE
The test_stream function is used in the train_push_prediction.py, but no implementation can be found

### ISSUE THREAD

**Issue by gcg6688** [rutgers-arc-lab/dipn#1]
Hi, @arc-l, could you mind telling me where the test_stream function is?
Hope for your reply :-)

**Comment by baichuan05** [comment]
Hi @gcg6688,

The argument test_stream is deprecated and should be removed. This is a testing argument that can plot the push prediction results. So, you may try `--symmetric_diff ` to get some plots. 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/20850928/184593250-68edad70-52d2-42f1-9650-f099a53ca91f.png">


Also, you can check this [file](https://github.com/arc-l/vft/blob/main/train_push_prediction.py) for a more recent push prediction training and plotting. 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/20850928/184593300-dbe10b67-6bf9-4ce1-af4c-9afa2bbeb2e4.png">

Best,
Baichuan
