### ISSUE TITLE
What is the reason for this?

### ISSUE THREAD

**Issue by yhshao56** [rutgers-arc-lab/dipn#2]
![1](https://user-images.githubusercontent.com/98634940/189602162-7f70dbaf-bb3f-4117-b2f0-f2952db23527.PNG)
Can somebody help me solve this problem?

**Comment by Xinqi-L** [comment]
try this:
M = cv2.getRotationMatrix2D((int(i_prev_poses[pi * 2 + 1]), int(i_prev_poses[pi * 2])), -i_output[pi * 3 + 2], 1)

**Comment by yhshao56** [comment]
thanks for yours answer

Xinqi-L ***@***.***> 於 2022年11月10日 週四 上午10:38寫道：
