### ISSUE TITLE
how to generate database for train_maskrcnn.py?

### ISSUE THREAD

**Issue by Xinqi-L** [rutgers-arc-lab/dipn#3]
Thanks for your wonderful work!

I got troubled when trying to train maskrcnn.pth. It seems that **'logs/random-maskrcnn/data'** and  **'logs/random-maskrcnn-hard/data'** is required. But I'm not sure how to generate the database properly.

Could you kindly share your instrusctions on how to generate database, or, if possible, your database for training?

Thanks!

**Comment by baichuan05** [comment]
Hi @Xinqi-L,

You may take a look at the file [create_mask_rcnn_image.py](https://github.com/arc-l/dipn/blob/main/create_mask_rcnn_image.py)

It will randomly generate some objects and save images for training maskrcnn.

Best,
Baichuan

**Comment by Xinqi-L** [comment]
Thanks a lot!
I'm trying!

**Comment by Xinqi-L** [comment]
'create_mask_rcnn_image.py' does helps!

But now I can't find proper script for generating dataset for train_foreground.py. Is there any suggestions?

Thanks for your kindness!
