### ISSUE TITLE
Why "abs(d_a) < 120" in dataset.py?

### ISSUE THREAD

**Issue by Xinqi-L** [rutgers-arc-lab/dipn#4]
I came across a problem when running "train_push_prediction.py".
I used my dataset generated by "collect_data.py" and extracted 30% of it into the test set named "data-test". However, problem occured here:
(https://github.com/arc-l/dipn/blob/e50bf46ddb604b7a675e32320900f06f45154261/dataset.py#L670)

My question: Is "assert abs(d_a) < 120" necessary? May I simply comment this line?

Thanks in advance!

**Comment by baichuan05** [comment]
If I recall correctly, in most case, a single straight push will not cause a rotation over 120 degrees, otherwise, it could be the simulation is not correct in such case. You can continue collect remaining data by removing that specific case.
